site_name: 'Human-AI Interaction (Fall 2021)'
site_url: 'https://haiicmu.github.io/'
site_description: 'Human-AI Interaction (Fall 2021)'
site_author: 'Steven Wu & Haiyi Zhu'

theme:
  name: 'mkdocs'
  language: 'en'
  logo: 'assets/images/favicon.png'
  favicon: 'assets/images/favicon.png'

nav:
  - Home: 'index.md'
  - Schedule: 'calendar.md'
  - Assignments:
    - Assignment 1: 'hw/hw1.md'
  - Resources:
    - Python: 'resources/python.md'
    - Related courses: 'resources/others.md'